input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => "\[%{TIMESTAMP_ISO8601:log_time}\] %{LOGLEVEL:level}\s+ip=%{IPORHOST:client_ip}\s+method=%{WORD:http_method}\s+uri=%{DATA:uri}\s+status=%{INT:http_status}\s+response_time_ms=%{INT:response_time_ms}\s+user_agent=\"%{DATA:user_agent}\"\s+message=\"%{GREEDYDATA:log_message}\""
    }
    overwrite => ["message"]
  }

  # 타임스탬프 파싱
  date {
    match => ["log_time", "yyyy-MM-dd'T'HH:mm:ss.SSSZ"]
    target => "@timestamp"
  }

  # 타입 변환
  mutate {
    convert => {
      "http_status" => "integer"
      "response_time_ms" => "integer"
    }
    remove_field => [ "log_time" ]  # 파싱 후 원본 제거
  }

  # 인덱스 이름에 날짜 추가
  mutate {
    add_field => { "log_type" => "http_access" }
  }
}

output {
  stdout {
    codec => rubydebug
  }

  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "PL1*9JC6-aU9H1OzKycc"
    ssl => true
    ssl_verification_mode => "none"
    index => "app-http-logs-%{+YYYY.MM.dd}"  # bankpipeline → 동적 인덱스
  }
}
